kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim
  annotations:
    volume.beta.kubernetes.io/storage-class: rook-ceph-block-karan
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
